Py 3.10 image
guzman-raphael/djbase pull request #33
Opened 2022-03-30 19:54 UTC by A-Baji

2022-04-01 20:38 UTC, guzman-raphael requested changes
@A-Baji Awesome, nice work. :+1: 

Minor point for your test since it seemed like a typo.

2022-04-01 20:38 UTC, guzman-raphael commented on tests/main.sh
> +	SIZE_LIMIT=6400
Probably meant:

```suggestion
	SIZE_LIMIT=640
```

2022-04-01 20:47 UTC, A-Baji commented on tests/main.sh
> +	SIZE_LIMIT=6400
Woops! Fixed :+1:

2022-04-04 14:44 UTC, guzman-raphael approved these changes

2022-04-04 14:44 UTC, merged